language: php

sudo: false

matrix:
  include:
    - php: 7.1
      env: SYMFONY_VERSION=2.7.*
    - php: 7.1
      env: SYMFONY_VERSION=2.8.*
    - php: 7.1
      env: SYMFONY_VERSION=3.3.*
    - php: 7.2
  allow_failures:
    - php: 7.2

env:
  global:
    - SYMFONY_VERSION=""

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/security:$SYMFONY_VERSION symfony/config:$SYMFONY_VERSION symfony/http-foundation:$SYMFONY_VERSION symfony/dependency-injection:$SYMFONY_VERSION symfony/http-kernel:$SYMFONY_VERSION; fi

install:
  - composer install

script:
  - bin/phpspec run -fpretty --verbose
