services:
    hexanet_monolog_extra.gelf.transport:
        class: Gelf\Transport\UdpTransport
        arguments:
            - %hexanet_monolog_extra.gelf.host%
            - %hexanet_monolog_extra.gelf.port%

    hexanet_monolog_extra.gelf.publisher:
        class: Hexanet\Common\LogBundle\Gelf\Publisher
        arguments:
            - @hexanet_monolog_extra.gelf.transport

    hexanet_monolog_extra.listener.console_exception:
        class: Hexanet\Common\LogBundle\EventListener\ConsoleExceptionListener
        arguments:
            - @logger

    hexanet_monolog_extra.listener.request_response:
        class: Hexanet\Common\LogBundle\EventListener\RequestResponseListener
        arguments:
            - @hexanet_monolog_extra.logger.request
            - @hexanet_monolog_extra.logger.response

    hexanet_monolog_extra.listener.uid_to_response:
        class: Hexanet\Common\LogBundle\EventListener\UidResponseListener
        arguments:
            - @hexanet_monolog_extra.logger.provider.uid

    hexanet_monolog_extra.logger.provider.uid.uniq:
        class: Hexanet\Common\LogBundle\Provider\Uid\UniqidProvider

    hexanet_monolog_extra.logger.provider.uid.apache_unique_id:
        class: Hexanet\Common\LogBundle\Provider\Uid\ApacheUniqueIdProvider

    hexanet_monolog_extra.logger.provider.session.symfony:
        class: Hexanet\Common\LogBundle\Provider\Session\SymfonySessionIdProvider
        arguments:
          - %hexanet_monolog_extra.session_start%
          - @?session

    hexanet_monolog_extra.logger.provider.user.symfony:
        class: Hexanet\Common\LogBundle\Provider\User\SymfonyUserProvider
        arguments:
            - @security.token_storage

    hexanet_monolog_extra.logger.processor.username:
        class: Hexanet\Common\LogBundle\Processor\UserProcessor
        arguments:
            - @hexanet_monolog_extra.logger.provider.user

    hexanet_monolog_extra.logger.processor.session_id:
        class: Hexanet\Common\LogBundle\Processor\SessionIdProcessor
        arguments:
            - @hexanet_monolog_extra.logger.provider.session

    hexanet_monolog_extra.logger.processor.additions:
        class: Hexanet\Common\LogBundle\Processor\AdditionsProcessor
        arguments:
            - []

    hexanet_monolog_extra.logger.processor.psr_log_message:
        class: Monolog\Processor\PsrLogMessageProcessor

    hexanet_monolog_extra.logger.processor.process_id:
        class: Monolog\Processor\ProcessIdProcessor

    hexanet_monolog_extra.logger.processor.uid:
        class: Hexanet\Common\LogBundle\Processor\UidProcessor
        arguments:
            - @hexanet_monolog_extra.logger.provider.uid

    hexanet_monolog_extra.logger.request:
        class: Hexanet\Common\LogBundle\Logger\Request\RequestLogger
        arguments:
            - @logger

    hexanet_monolog_extra.logger.response:
        class: Hexanet\Common\LogBundle\Logger\Response\ResponseLogger
        arguments:
            - @logger
