services:
    _defaults:
        autowire: true
        public: false
        autoconfigure: true
        bind:
            $startSession: "%hexanet_monolog_extra.session_start%"
            $session: '@?session'

    Hexanet\Common\MonologExtraBundle\:
        resource: '../../{Logger,EventListener,Processor,Provider}'
